"""
Configuration Commands for Bullseye

Commands for managing configuration and user directories.
"""
import sys
from pathlib import Path
from typing import Optional

import click
from rich.console import Console
from rich.table import Table
from rich.prompt import Prompt, Confirm

console = Console()


DEFAULT_CONFIG = """# Bullseye Configuration File
# Generated by bullseye new-config

# ==================== Basic Settings ====================
max_open_trades: 5
stake_currency: USDT
stake_amount: 100
tradable_balance_ratio: 0.99
fiat_display_currency: USD
dry_run: true
dry_run_wallet: 1000

# ==================== Market Type ====================
# Options: auto, crypto, stock, future
market_type: auto

# ==================== Settlement Configuration ====================
settlement:
  mode: auto
  overrides: {}
  default: t0

# ==================== Exchange Configuration ====================
exchange:
  name: binance
  key: ""
  secret: ""
  passphrase: ""
  sandbox: false
  ccxt_config: {}
  ccxt_async_config: {}

# ==================== Stock Configuration (China) ====================
stock:
  gateway: xtp
  userid: ""
  password: ""
  client_id: 1
  session_id: 1
  md_ip: "120.27.164.138"
  md_port: 6002
  td_ip: "120.27.164.138"
  td_port: 6001
  datafeed: tushare
  tushare_token: ""

# ==================== Futures Configuration (China) ====================
future:
  gateway: ctp
  userid: ""
  password: ""
  brokerid: "9999"
  td_address: "tcp://180.168.146.187:10130"
  md_address: "tcp://180.168.146.187:10131"
  appid: ""
  auth_code: ""
  product_info: ""

# ==================== Pairlist Configuration ====================
pairlist:
  - method: StaticPairList
    config:
      pairs:
        - BTC/USDT
        - ETH/USDT
        - BNB/USDT

# ==================== Strategy Configuration ====================
strategy: SampleStrategy
strategy_path: user_data/strategies

# ==================== Backtesting Configuration ====================
backtest:
  timeframe: 5m
  timerange: null
  max_open_trades: 5
  position_stacking: false
  fee: 0.001

# ==================== Hyperopt Configuration ====================
hyperopt:
  epochs: 100
  spaces: all
  loss_function: SharpeHyperOptLoss
  hyperopt_jobs: -1
  target_trades: 30
  min_trades: 1

# ==================== Database Configuration ====================
db_url: sqlite:///user_data/tradesv3.sqlite

# ==================== Telegram Configuration ====================
telegram:
  enabled: false
  token: ""
  chat_id: ""
  notification_settings:
    status: warning
    warning: on
    startup: on
    entry: on
    entry_fill: on
    exit: on
    exit_fill: on
    protection_trigger: on
    show_candle: off
    strategy_msg: on

# ==================== API Server Configuration ====================
api_server:
  enabled: false
  listen_ip: 127.0.0.1
  listen_port: 8080
  verbosity: error
  enable_openapi: true
  jwt_secret_key: ""
  ws_token: ""
  CORS_origins: []
  username: ""
  password: ""

# ==================== Webhook Configuration ====================
webhook:
  enabled: false
  url: ""
  format: json
  retry_count: 3
  timeout: 10

# ==================== Logging Configuration ====================
logfile: user_data/logs/bullseye.log
log_level: INFO

# ==================== Additional Settings ====================
internals:
  process_throttle_secs: 5

# ==================== Protections ====================
protections: []
"""


@click.command(name='create-userdir')
@click.option('--userdir', '-u', type=str, help='User directory path')
@click.option('--overwrite', is_flag=True, help='Overwrite existing files')
def create_userdir(userdir: Optional[str], overwrite: bool):
    """
    Create user data directory structure
    
    Creates the standard user_data directory structure for Bullseye.
    
    Examples:
        bullseye create-userdir
        bullseye create-userdir --userdir /path/to/user_data
        bullseye create-userdir --overwrite
    """
    userdir = userdir or "user_data"
    userdir_path = Path(userdir)

    console.print(f"[green]Creating user directory structure at: {userdir_path.absolute()}[/green]\n")

    # Define directory structure
    directories = [
        "",
        "backtest_results",
        "data",
        "data/binance",
        "hyperopts",
        "logs",
        "notebooks",
        "plot",
        "strategies",
    ]

    created_count = 0
    existing_count = 0

    for dir_name in directories:
        dir_path = userdir_path / dir_name
        if dir_path.exists():
            existing_count += 1
            console.print(f"[blue]  Exists: {dir_path}[/blue]")
        else:
            dir_path.mkdir(parents=True, exist_ok=True)
            created_count += 1
            console.print(f"[green]✓ Created: {dir_path}[/green]")

    # Create .gitkeep files
    for dir_name in directories:
        if dir_name:  # Skip root
            gitkeep = userdir_path / dir_name / ".gitkeep"
            if not gitkeep.exists():
                gitkeep.touch()

    console.print("\n[green]✓ Directory structure created successfully![/green]")
    console.print(f"  Created: {created_count}, Existing: {existing_count}")


@click.command(name='new-config')
@click.option('--config', '-c', type=str, help='Configuration file path')
@click.option('--market-type', type=click.Choice(['crypto', 'stock', 'future']), help='Market type')
@click.option('--exchange', type=str, help='Exchange name')
@click.option('--non-interactive', is_flag=True, help='Non-interactive mode')
def new_config(config: Optional[str], market_type: Optional[str], exchange: Optional[str], non_interactive: bool):
    """
    Create new configuration file interactively
    
    Guides you through creating a new configuration file with
    interactive prompts for common settings.
    
    Examples:
        bullseye new-config
        bullseye new-config --config myconfig.yaml
        bullseye new-config --market-type crypto --exchange binance
    """
    config_path = Path(config or "config.yaml")

    if config_path.exists() and not non_interactive:
        if not Confirm.ask(f"[yellow]Configuration file '{config_path}' already exists. Overwrite?[/yellow]"):
            console.print("[blue]Cancelled.[/blue]")
            return

    console.print("[bold green]Creating new Bullseye configuration[/bold green]\n")

    if non_interactive:
        # Use default configuration
        config_content = DEFAULT_CONFIG
    else:
        # Interactive configuration
        config_data = {}

        # Market type selection
        if not market_type:
            market_type = Prompt.ask(
                "Select market type",
                choices=["crypto", "stock", "future"],
                default="crypto"
            )
        config_data['market_type'] = market_type

        # Exchange configuration
        if market_type == "crypto":
            if not exchange:
                exchange = Prompt.ask(
                    "Select exchange",
                    choices=["binance", "okx", "bybit", "gate.io", "kucoin"],
                    default="binance"
                )
            config_data['exchange_name'] = exchange

            # Dry run mode
            dry_run = Confirm.ask("Enable dry-run mode (paper trading)?", default=True)
            config_data['dry_run'] = dry_run

            # Stake amount
            stake_amount = Prompt.ask("Stake amount per trade", default="100")
            config_data['stake_amount'] = stake_amount

            # Max open trades
            max_trades = Prompt.ask("Maximum open trades", default="5")
            config_data['max_open_trades'] = int(max_trades)

            # Telegram
            use_telegram = Confirm.ask("Enable Telegram notifications?", default=False)
            if use_telegram:
                console.print("[yellow]Please configure Telegram settings in the generated config file.[/yellow]")

        elif market_type == "stock":
            console.print("[yellow]Stock market configuration - please edit the config file for gateway details.[/yellow]")
            config_data['exchange_name'] = "xtp"

        elif market_type == "future":
            console.print("[yellow]Futures market configuration - please edit the config file for CTP details.[/yellow]")
            config_data['exchange_name'] = "ctp"

        # Generate config content
        config_content = generate_config_content(config_data)

    # Write configuration file
    try:
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write(config_content)
        console.print(f"\n[green]✓ Configuration file created: {config_path.absolute()}[/green]")
    except Exception as e:
        console.print(f"\n[red]Error creating configuration file: {e}[/red]")
        sys.exit(1)

    console.print("\n[yellow]Next steps:[/yellow]")
    console.print(f"  1. Edit the configuration: {config_path}")
    console.print("  2. Set your API keys and secrets")
    console.print("  3. Run: bullseye trade --dry")


def generate_config_content(config_data: dict) -> str:
    """Generate configuration content based on user input."""
    content = DEFAULT_CONFIG

    # Update with user settings
    if 'market_type' in config_data:
        content = content.replace("market_type: auto", f"market_type: {config_data['market_type']}")

    if 'exchange_name' in config_data:
        content = content.replace("name: binance", f"name: {config_data['exchange_name']}")

    if 'dry_run' in config_data:
        dry_run_str = "true" if config_data['dry_run'] else "false"
        content = content.replace("dry_run: true", f"dry_run: {dry_run_str}")

    if 'stake_amount' in config_data:
        content = content.replace("stake_amount: 100", f"stake_amount: {config_data['stake_amount']}")

    if 'max_open_trades' in config_data:
        content = content.replace("max_open_trades: 5", f"max_open_trades: {config_data['max_open_trades']}")

    return content


@click.command(name='show-config')
@click.option('--config', '-c', type=str, help='Configuration file path')
@click.option('--show-defaults', is_flag=True, help='Show default values')
@click.option('--print-json', is_flag=True, help='Output as JSON')
def show_config(config: Optional[str], show_defaults: bool, print_json: bool):
    """
    Show resolved configuration
    
    Displays the configuration with all default values resolved.
    
    Examples:
        bullseye show-config
        bullseye show-config --config myconfig.yaml
        bullseye show-config --show-defaults
        bullseye show-config --print-json
    """
    config_path = config or "config.yaml"

    try:
        from ..configuration import Config
        config_obj = Config(config_path)
    except FileNotFoundError:
        console.print(f"[red]Configuration file not found: {config_path}[/red]")
        sys.exit(1)
    except Exception as e:
        console.print(f"[red]Error loading configuration: {e}[/red]")
        sys.exit(1)

    if print_json:
        # Output as JSON
        import json
        config_dict = config_obj.to_dict() if hasattr(config_obj, 'to_dict') else vars(config_obj)
        console.print(json.dumps(config_dict, indent=2, default=str))
        return

    console.print("[bold green]Bullseye Configuration[/bold green]\n")

    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("Setting", style="cyan")
    table.add_column("Value", style="green")

    # Basic settings
    table.add_row("Market Type", str(config_obj.get('market_type', 'auto')))
    table.add_row("Exchange", str(config_obj.get('exchange_name', 'N/A')))
    table.add_row("Strategy", str(config_obj.get('strategy', 'N/A')))
    table.add_row("Dry Run", str(config_obj.get('dry_run', True)))
    table.add_row("Max Open Trades", str(config_obj.get('max_open_trades', 5)))
    table.add_row("Stake Amount", str(config_obj.get('stake_amount', 'unlimited')))
    table.add_row("Stake Currency", str(config_obj.get('stake_currency', 'USDT')))

    # Database
    db_url = config_obj.get('db_url', 'sqlite:///user_data/tradesv3.sqlite')
    table.add_row("Database", db_url)

    # Telegram
    telegram_enabled = config_obj.get('telegram.enabled', False)
    table.add_row("Telegram", "Enabled" if telegram_enabled else "Disabled")

    # API Server
    api_enabled = config_obj.get('api_server.enabled', False)
    table.add_row("API Server", "Enabled" if api_enabled else "Disabled")

    console.print(table)

    if show_defaults:
        console.print("\n[yellow]Full configuration with defaults:[/yellow]")
        # This would show the complete merged configuration
        console.print("[dim](Use --print-json for complete configuration)[/dim]")
